### ISSUE TITLE
Class 'Manager' not found

### ISSUE THREAD

**Issue by Cdric49** [daftspunk/dishsmith#4]
Hello,

I noticed with the last OctoberCMS, your plugin/template doesn't work (release #136).
It uses the Auth class which is deprecated.

Instead, OctoberCMS seems to use library/src/Auth/Manager.php

I don't know how to modify your code to use Manager instead of Auth.

Sincerly,

Cédric

**Comment by daftspunk** [comment]
This doesn't make sense.

`Auth` is an alias for `October\Rain\Auth\Manager`

**Comment by Cdric49** [comment]
So, I don't understand what it's wrong with my installation.
I followed the instruction and the result : http://cid.uni.me
The plugin is enable.
Have you any idea ?
Thanks

**Comment by MarvynHaynes** [comment]
Installing the RainLab User plugin has worked for me.

**Comment by daftspunk** [comment]
Caused by #5
